### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zvyn** [nodeschool/wellington#11]
I know nobody likes the legal stuff, but experience tells me we should add an open source license early in the process. Since this project seems to be mainly about providing content and art (the logo etc.) I would propose a Creative Commons license.

The questions we would need to agree on (adapted from https://creativecommons.org/choose/) :
- Allow adaptations of your work to be shared?
  Possible answers: yes, only if shared under a similar license, no
- Allow commercial uses of your work?
  Yes, or no.

You can safely ignore my opinion here since I didn't contribute content yet, however I would prefer the open source way: Allowing commercial adaptions if they are shared with a similar license:
"This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

**Comment by ahdinosaur** [comment]
:+1: thanks for this discussion @zvyn. i'm also keen to use the [CC-BY-SA license](https://creativecommons.org/licenses/by-sa/4.0/).

@ashlynbaum since you've contributed the initial website content, is this cool with you?

**Comment by ashlynbaum** [comment]
@ahdinosaur  Yep I'm fine with this. Do it.
